/* gravity_params.h — AUTO GENERATED by scripts/gravity_identification.py
 * Date: 2026-03-27 11:41:33
 * Mode: remedy+bias nonlinear phases
 * Fitting MAE (Nm): J1=1.5846  J2=1.7246  J3=0.3164
 * R²: J1=0.8987  J2=0.4644  J3=0.3098
 *
 * tau_g1 = GC_BIAS_J1 + A1*cos(q1+PHI1) + A2*cos(q1+q2+PHI2) + A3*cos(q1+q2+q3+PHI3)
 * tau_g2 = GC_BIAS_J2 + B1*cos(q1+q2+PSI1) + B2*cos(q1+q2+q3+PSI2)
 * tau_g3 = GC_BIAS_J3 + C1*cos(q1+q2+q3+ZETA1)
 */
#ifndef GRAVITY_PARAMS_H
#define GRAVITY_PARAMS_H

#define GC_BIAS_J1 -5.630414f
#define GC_BIAS_J2 2.290561f
#define GC_BIAS_J3 0.344724f

#define GC_A1    -10.681515f
#define GC_A2    0.315461f
#define GC_A3    3.710171f
#define GC_PHI1  -0.570128f
#define GC_PHI2  0.238959f
#define GC_PHI3  -1.979277f

#define GC_B1    3.525888f
#define GC_B2    3.344917f
#define GC_PSI1  1.908724f
#define GC_PSI2  0.175877f

#define GC_C1    0.372969f
#define GC_ZETA1 1.350017f

#define GC_SIGN_J0   0
#define GC_SIGN_J1  +1
#define GC_SIGN_J2  +1
#define GC_SIGN_J3  +1

#define GC_MAX_TFF   10.0f

#endif /* GRAVITY_PARAMS_H */
